#' Add metadata details to the README file
#'
#' @description
#' A short description...
#'
#' @param meta \code{data.frame} generated by one of the *get_* functions containing metadata info.
#' You can also pass you own data frame, provided it contain all necessary collumns (see details).
#'
#' @details
#' If you pass your own data frame, it should contain only one line and the following collumns:
#' - description: the description of the dataset
#' - reponame: the name of the repository where the dataset was downloaded
#' - doi: the DOI
#' - date: when the dataset was published
#' - authors: the author(s) of the dataset
#' - license: the license of the dataset
#'
#'
#' @return the edited README file
#' @export
#'
#' @examples
#' \dontrun{
#' add_metadata_readme(meta = metadata_obj)
#' }
add_metadata_readme <- function(meta){

  nl <- paste0(
    meta$description,"\n\n",
    paste0("It was published in ", meta$reponame, " (https://doi.org/", meta$doi, "), and was authored by ", meta$authors, "."),"\n\n",
    paste0("The first version of the dataset is available since ", format(as.Date(meta$date), "%Y-%m-%d"),
           " and is licensed under a ", meta$license, " license."),
    collapse = "\n"
  )

  ol <- readLines("README.md")
  ol <- gsub("<!-- DATASET_METADATA -->", nl, ol)
  writeLines(ol, "README.md")

  cli::cli_alert_success("Metadata added to README.md")

  return(invisible(NULL))
}
